### PR TITLE
Remove redis lock

### PR DESCRIPTION
**Pull request by insacuri**
# Motivation and Context

# What has changed

# How to test?

# Links

### CODE REVIEW

**Review by akssinhaamit — COMMENTED** [review]
Is it duplication of https://github.com/ONSdigital/rm-collection-exercise-service/pull/209/files? If yes please close this PR

**Comment by insacuri** [comment]
> Is it duplication of https://github.com/ONSdigital/rm-collection-exercise-service/pull/209/files? If yes please close this PR

The 2nd PR was branched off of this and has additional code removed.  This PR is tested, the other one isn't.  I want to deliver it in 2 bits to make sure nothing breaks.

**Comment by akssinhaamit** [comment]
> was branched off of this and has additional code removed. This PR is tested

If the second PR was branched of this do we need this PR then? The new PR should cover both isn't?

**Review by akssinhaamit — APPROVED** [review]

**Pull request merged**
