### PR TITLE
RAS-920 Collection exercise change mockito-inline to mockito-core for Java

### PR DESCRIPTION
**Pull request by arroyoAle**
# What and why?
Swaps mockito inline to mockito core and adding bytebuddy to allow it to run
# How to test?
- run `mvn clean verify`
- deploy to your env and run the acceptance tests
# Jira
https://jira.ons.gov.uk/browse/RAS-920

### CODE REVIEW

**Review by anwilkie — APPROVED** [review]
Tests pass, so I will approve.

**Review by matthew-robinson-ons — APPROVED** [review]
All looks good to me

**Pull request merged**
