### PR TITLE
Remove EQ version

### PR DESCRIPTION
**Pull request by mfcrocker**
# What and why?
EQ v2 has been dead for some time, this removes the concept of a particular version.

# How to test?

# Jira
RAS-1144

### CODE REVIEW

**Review by LJBabbage — CHANGES_REQUESTED** [review]
I don't think we can reformat and do the change at the same time +1,092 -1,017 makes it hard to tell what has changed

**Comment by mfcrocker** [comment]
> I don't think we can reformat and do the change at the same time +1,092 -1,017 makes it hard to tell what has changed

As discussed I've tried and can't provide a nicer diff. CEEndpoint removes `patchCollectionExerciseEqVersion` and the CEEndpointUnitTests removes `testPatchCollectionExerciseEQVersion` - there shouldn't be any other non-formatting changes in those files

**Comment by LJBabbage** [comment]
> > I don't think we can reformat and do the change at the same time +1,092 -1,017 makes it hard to tell what has changed
> 
> As discussed I've tried and can't provide a nicer diff. CEEndpoint removes `patchCollectionExerciseEqVersion` and the CEEndpointUnitTests removes `testPatchCollectionExerciseEQVersion` - there shouldn't be any other non-formatting changes in those files

I can't seem to see patchCollectionExerciseEqVersion at all https://github.com/search?q=repo%3AONSdigital%2Frm-collection-exercise-service%20patchCollectionExerciseEqVersion&type=code. And tried EqVersion in my ide

**Review by LJBabbage — APPROVED** [review]

**Review by arroyoAle — APPROVED** [review]
Looks good and tested and works as expected

**Pull request merged**
