### PR TITLE
replacing pubsub impl to spring integration

### PR DESCRIPTION
**Pull request by creativeappdevamit**
# What and why?

# How to test?

# Trello
https://trello.com/c/cZwIJ450/870-implement-spring-integration-for-pubsub-between-collection-exercise-and-case-service

### CODE REVIEW

**Review by insacuri — CHANGES_REQUESTED** [review]
I'm almost certain that all of this can go once the v2 stuff is live.  From a code standpoint it looks good and could go in; Though I think we should close this PR as we're imminently going to be deleting the code that handles samples going to CE and publishing samples to case from CE

**Comment by creativeappdevamit** [comment]
> I'm almost certain that all of this can go once the v2 stuff is live. From a code standpoint it looks good and could go in; Though I think we should close this PR as we're imminently going to be deleting the code that handles samples going to CE and publishing samples to case from CE

**Pull request closed without merging**
